[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "d5405d4888a5cfa938dba8505109b9dc1eb3e1d6"
os = "macos"

    [[LV2Host.download]]
    sha256 = "a8ba9ad9fc9e9f5b0628e6ef9ff92e442b85057e70135bfb289279ee3aa5ad43"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.aarch64-apple-darwin.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "be926c299d993e087fb6be863c2a3e65992ebc6a"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "f38ed3be0d1d70d84d7724a4e55599630cf875a1149379c9129c89e89c08c709"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.aarch64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "58ad3f5dd23131fdadf3942c350cd33c9aa7d3b2"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "7f839a041608a37fead182024c6c8f12a4991c052ba96072c37604d6945a5a36"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.aarch64-linux-musl.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "360968eadcd04dd02a6353388b37f9db20168fb1"
os = "freebsd"

    [[LV2Host.download]]
    sha256 = "b3ef09c9b90b77f3c0a7a93cd51d7fa5e9b97a8c4114d50d74d9ae75612d3218"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.aarch64-unknown-freebsd.tar.gz"
[[LV2Host]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0557d9e578608db4eb436748b5a6cb8b0eb18936"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "4813541ce5dabc618e1d814145caf9b776bc0046bb2b11b06e10995dd3fc6e97"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.armv6l-linux-gnueabihf.tar.gz"
[[LV2Host]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60a0e03f96e349d4df4a8d646794e195863a9675"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "c3bb45fc68ab2638758ef8bb97546b79dda599725d3fa2b6542cd044c438f576"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.armv6l-linux-musleabihf.tar.gz"
[[LV2Host]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c99ce6790d5774d83e3a4ddff7bc69e5e9871401"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "03507e7970a2e21f8490b69476e9a6a2dc017e123a4d762d37913b5b175aa0c3"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.armv7l-linux-gnueabihf.tar.gz"
[[LV2Host]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b897956f7977c4d95805a8538f07951cc1b1c32b"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "c3161ea688e8f264b7c435af46ad130eee5d5bc1245ccacebc5ad11ec522b876"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.armv7l-linux-musleabihf.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "8c2da8969379673cdafa8647fdbb628b708e5657"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "636db5d32cd247e67ab799faeea86837015b6d4ddb1e5844035b16b128fbadf8"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.i686-linux-gnu.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "055f8dcd35a482acf1964a36878d41c0b226af2c"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "b98f0518e050a6478eb20997299c627354e4793c0d86715878fa08d0689b080b"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.i686-linux-musl.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "7d5513cc76abfbf51f217e489233091471da4a24"
os = "windows"

    [[LV2Host.download]]
    sha256 = "2db34d6c4aa903a531a77cad9dc3585dd7b2971466498f918273a720761eb50f"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.i686-w64-mingw32.tar.gz"
[[LV2Host]]
arch = "powerpc64le"
git-tree-sha1 = "fd9bc64eb8c8625816a9210a484f9250d8cf4cf6"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "ae4c2440c8fb935d27f1e44830531ea0912b0696a7a2c420af5e6f72ed8282c1"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.powerpc64le-linux-gnu.tar.gz"
[[LV2Host]]
arch = "riscv64"
git-tree-sha1 = "4cc7fed75ffbbe9f37ec8408282b77ec5c121c9d"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "78ea9b0c1f6e7d7ab392c7e35f130dd583e46dd38710dc29dac1e4fedb9f8906"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.riscv64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "1955b26b600ae70f41213ec6181107cca8f6f16a"
os = "macos"

    [[LV2Host.download]]
    sha256 = "1b36bfadc17ae79117cbe4d81e35c9f6ca6658e6d1b202cc36671898773116ec"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.x86_64-apple-darwin.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "b5328541b44a001cf6ce803e829506cf8ccf38d7"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "08ab3df1501a2624dab976e6abd5485b72c7e59ac66c7648fc12734fd0c7f4f0"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.x86_64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "7ce34bab71bb7f49aa0b4823d0a3c77407f46460"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "fe80d815161cdc258c1dcc85e556bf3f84b944c6d5c838fef4687765052a13ac"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.x86_64-linux-musl.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "195715c49b7f4ffa6341030bf2c1ec76dbb891bf"
os = "freebsd"

    [[LV2Host.download]]
    sha256 = "db1633f3d583a7b481f7eecfa04f8610e81838f385713b948fdd7bd47acf38aa"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "521afb1d37f9b03057af901e90e49a34ba240251"
os = "windows"

    [[LV2Host.download]]
    sha256 = "eb0d49a53983ed028f7bc6f413f1c7e34e9d48254c36a58e24050558bb994ebd"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.2.0+0/LV2Host.v1.2.0.x86_64-w64-mingw32.tar.gz"
