[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "fa006a864c7a15955007f793a0d1a473942d819e"
os = "macos"

    [[LV2Host.download]]
    sha256 = "5dd828f99e0855deb97fbc4ba44149788b5b28e393ef2f7d9fb1922023a4f968"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.aarch64-apple-darwin.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "d00c83f3d7f7d7f3cd4805001b6202caa97f009b"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "8cf686dad33ce4f0a68fb8b933761663ca9ec1474da993d0b5ded5b9bcf97cbe"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.aarch64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "b22a8e010bd5d9451eead5e1f74c4554797fdca7"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "3953c0ab1a3c86b85ba4b30b8c26eef7c4e62af27296ceb87c8c1662037cfc7b"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.aarch64-linux-musl.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "f401ab6191f198ecdb085c8a59bd244e99a28650"
os = "freebsd"

    [[LV2Host.download]]
    sha256 = "63df16727341fec49a6ef51c7579f70a3a2396671ad79bae9dbabb3ff96981c3"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.aarch64-unknown-freebsd.tar.gz"
[[LV2Host]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d755e8cc1e55276ff53ddbd8d4ba2deb8771557f"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "d4b41a044842857dad75b36745efbccdcdd98e3b7341c296de77370dea51f082"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.armv6l-linux-gnueabihf.tar.gz"
[[LV2Host]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75f586275d5ae65ebdfc5d2142a7f7e9577abbaf"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "d240b2427857f604040904594873d0613bd77d427245558f00523f224c6c7d92"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.armv6l-linux-musleabihf.tar.gz"
[[LV2Host]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c897bd2b72eb5a4b4b2aa17b51e44d748498c52"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "c76788e960c2cd4fae58f130cfd4ebc77cbf5f3fd6d10b58ab8e772199726826"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.armv7l-linux-gnueabihf.tar.gz"
[[LV2Host]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2abbe7433c8611df8e553c848cbc585ada83f71f"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "648bf6d89dcceb58268905f867a146b8391106ad4449f61f4b80a42a3be23dc4"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.armv7l-linux-musleabihf.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "100e56e0ca30578066b2ce9e8dd497518258b268"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "c49ab7fc6ccd1ae64a77a149214d8169e091159a63c3c21d547e1529c38c6098"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.i686-linux-gnu.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "2ebcfdf9f02c2a4a8262fd38e293c5b82d94271a"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "be1be93a49e0890806c7cb8ab0916fd88a4a9105a5089d34831bf7e40fba5b60"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.i686-linux-musl.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "a956f8bfe04c56e2ae0b700e67f3536359d8e5bf"
os = "windows"

    [[LV2Host.download]]
    sha256 = "2660d50f22a4adfb14be9b613fc7e537cb3772c392ae766bf382a3ced986b115"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.i686-w64-mingw32.tar.gz"
[[LV2Host]]
arch = "powerpc64le"
git-tree-sha1 = "5f24e8f4166f7c54c865b23db981b846c688915d"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "c6502af58eef1c41fbdb3d257f6693aa331618d9bead36c5df2fc3320c5f30ce"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.powerpc64le-linux-gnu.tar.gz"
[[LV2Host]]
arch = "riscv64"
git-tree-sha1 = "245f63cc840237a295eb7c28b503ba99ee77b900"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "6fe52e53e554bd774463a51aa9317b23fb60854069f5bc65689b9348529ec506"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.riscv64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "1685952dc528691e6695b69277f1160ce5dfc436"
os = "macos"

    [[LV2Host.download]]
    sha256 = "af7ef11714fa3d8632f3203c2fda78e856aadf4f794294b4ec803c4a8856bdff"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.x86_64-apple-darwin.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "e72d58b979d6973f91f4d239078a2b6deb2efd4d"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "8ebd3b7cf05da306817d67be090f0987be7ec2b25f5acc08dc9717378ee500fd"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.x86_64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "bc90aaac072a20ba9ec51f70cc311758e4ada644"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "b113f5b60bcbb04943bc28dfa002e76bb3ea723c66d0f74350ff2534dd4fca8a"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.x86_64-linux-musl.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "dad529acf2461c4d8f8e2f99889abb0f86029b77"
os = "freebsd"

    [[LV2Host.download]]
    sha256 = "cf5a608cbdfe73ffc7f758a65b5a8a7fe1bbe97e7f69312db00e4339133fa348"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.x86_64-unknown-freebsd.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "3e3e680727b2b90ac0d432c7cc3f3cff624457a9"
os = "windows"

    [[LV2Host.download]]
    sha256 = "ca301c5c28edea9a2b4bd7d68b9b3633b557289fd0c7ba6dec5bf01a135160dd"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.1+0/LV2Host.v1.1.1.x86_64-w64-mingw32.tar.gz"
