[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "f9887e69ee041c93392ecf75eb0371ecf4544834"
os = "macos"

    [[LV2Host.download]]
    sha256 = "b206dd9338f51d0c76ce8da49b4605b2531ffb414357917749d0ed107d15e586"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.aarch64-apple-darwin.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "c4ad73bf5cb0228a02301fded23270d6f11145b9"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "48a2ef897a06ed00fb9606b9afcee67d5af1b34f8d25b619b79946212c6d2721"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.aarch64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "24f117e8c7d445a4f77b47b6f8a5d6cbbf59c734"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "b2ef6827d2c8d5c3e8566e395d58ed91d99ce58edb8f6364449d036090262bc1"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.aarch64-linux-musl.tar.gz"
[[LV2Host]]
arch = "aarch64"
git-tree-sha1 = "50f81543df7bdf6392a06ce36d792a70782039d1"
os = "freebsd"

    [[LV2Host.download]]
    sha256 = "1f54bb1ffc942fb1d07d7b639534dfb69e311fa0f2a025c30298f6124fc0a820"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.aarch64-unknown-freebsd.tar.gz"
[[LV2Host]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23fa669cdc40bd5ee2d2f8504c78f3daa423bf23"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "fb1a8027bb94b589c4c45f287c360e66e78355f45968d15961ad0f1114ea6f82"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.armv6l-linux-gnueabihf.tar.gz"
[[LV2Host]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d32a75070d32d9348e0ac9bc3c0965a08b62b36d"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "ad00824f716f35074d63c8e62af0ace23a1b3afbacf49754701178802f113e20"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.armv6l-linux-musleabihf.tar.gz"
[[LV2Host]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c9121828ec52398536e8bc8fed223f57451ebfbb"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "2f2a5bc799cb3addb1b794053e934fffb3cce2992fc3f444a7897dde0d26020f"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[LV2Host]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6fa2dac2dbc13cd0f57d12276793dfa5354bf31"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "7ae1451a398e148b6af37d8a2b6559b4013cfc2f5586f5a8a6d9956b7fe380a7"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "2d56aff05f7c2e8040fe5de7b5d05e012b669535"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "94a1fee1de92ffdcf9dd573bc486e3c1dd4e89e8ad555b658a9cb7357d13f2ee"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.i686-linux-gnu.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "5f3a6259d235e10b3477bc93ea4458784d47557e"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "39890bd32de54104b333e9767fbf1fdd515c841b378d1b8c1ca4cf5f64deed10"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.i686-linux-musl.tar.gz"
[[LV2Host]]
arch = "i686"
git-tree-sha1 = "437ef9ee1eb60b30dc2676f3c37079affb930fc2"
os = "windows"

    [[LV2Host.download]]
    sha256 = "39c4c7214abd6e126dbf4f3e3dec382c0899e6600774fa86eeee6a2157ddda82"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.i686-w64-mingw32.tar.gz"
[[LV2Host]]
arch = "powerpc64le"
git-tree-sha1 = "193c98f19c7b735adcba30c9ed2172b67745e626"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "1b15050e4394f2354b6f473249a521ab4be1c6a93fafea2090af5c35b50ff705"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[LV2Host]]
arch = "riscv64"
git-tree-sha1 = "c061f3cd069a72f108906f5b72cc7975b46f1e9c"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "631ea584777aa2af380a25a021313b1d848924126ce41140e9d6732cf60ad1fe"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.riscv64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "d42903ed3ef7a08ba01d410653bd0e199d140e66"
os = "macos"

    [[LV2Host.download]]
    sha256 = "d701cf6bdb5a1146de2fff6993a2d1af32c11bba86e76076eaf2e03ef17e6a90"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.x86_64-apple-darwin.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "a59fb1e2caac5234bd9a0c717fab1dad93c93f42"
libc = "glibc"
os = "linux"

    [[LV2Host.download]]
    sha256 = "f72601e3c99fcf8f033835c78fdd98651dc9f86c27738bdeb44e8c45ffa2d44f"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.x86_64-linux-gnu.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "583f033269fdf2bb8b6dc69087dc1f2abc8c688a"
libc = "musl"
os = "linux"

    [[LV2Host.download]]
    sha256 = "1f4979f3f877a6dc80c1fd10a2ab55ca111bd51fed90182a2e90e9e5b17d71ad"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.x86_64-linux-musl.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "727bec7f1bad7335b04a2ae64d94f1fdffe25855"
os = "freebsd"

    [[LV2Host.download]]
    sha256 = "d011d8b04e9cff6c7a0e51bc6f4fb86a640d35b60e6aad1737e0f83955309953"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.x86_64-unknown-freebsd.tar.gz"
[[LV2Host]]
arch = "x86_64"
git-tree-sha1 = "6a770ea5190357b598ec345685df7f252c3fabab"
os = "windows"

    [[LV2Host.download]]
    sha256 = "3c6027e2af422bce5878d55583ac3b4467941ef968e687b9c44edeb2595c80a6"
    url = "https://github.com/JuliaBinaryWrappers/LV2Host_jll.jl/releases/download/LV2Host-v1.1.0+0/LV2Host.v1.1.0.x86_64-w64-mingw32.tar.gz"
