# Autogenerated wrapper script for LV2Host_jll for i686-w64-mingw32
export liblv2_host

using Lilv_jll
JLLWrappers.@generate_wrapper_header("LV2Host")
JLLWrappers.@declare_library_product(liblv2_host, "liblv2_host.dll")
function __init__()
    JLLWrappers.@generate_init_header(Lilv_jll)
    JLLWrappers.@init_library_product(
        liblv2_host,
        "bin\\liblv2_host.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
