# Autogenerated wrapper script for LV2Host_jll for x86_64-apple-darwin
export liblv2_host

using Lilv_jll
JLLWrappers.@generate_wrapper_header("LV2Host")
JLLWrappers.@declare_library_product(liblv2_host, "@rpath/liblv2_host.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Lilv_jll)
    JLLWrappers.@init_library_product(
        liblv2_host,
        "lib/liblv2_host.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
